AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Boilerplate Using TypeScript

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
    Runtime: nodejs18.x
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  SuggestRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      FunctionName: 'Suggest Recipe'
      CodeUri: src/suggest-recipe/
      Environment:
        Variables:
          OPENAI_API_KEY: OPENAI_API_KEY
      Events:
        Api:
          Type: Api
          Properties:
            Path: /suggest-recipe
            Method: post
