AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  local-test

Globals:
  Function:
    Timeout: 25
    MemorySize: 256
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  TextForImage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: suggestRecipe/
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          OPEN_AI_API_KEY: OPEN_AI_API_KEY
      Events:
        Api:
          Type: Api
          Properties:
            Path: /suggest-recipe
            Method: post
